---
# tasks file for while_true_do.sys_sudo

- name: Manage sudo Packages
  package:
    name: "{{ wtd_sys_sudo_package }}"
    state: "{{ wtd_sys_sudo_package_state }}"
  become: true
  tags:
    - sudo
    - package

- name: Configure sudo users in /etc/sudoers.d/*
  template:
    src: "sudoers.d.j2"
    dest: "/etc/sudoers.d/{{ item.name }}"
    mode: 0400
    owner: "root"
    group: "root"
    validate: "visudo -cf %s"
  loop: "{{ wtd_sys_sudo_conf_sudoers }}"
  become: true
  when:
    - wtd_sys_sudo_package_state != "absent"
  tags:
    - sudo
    - configuration

- name: Configure sudo users in /etc/sudoers
  template:
    src: "sudoers.j2"
    dest: "/etc/sudoers"
    mode: 0400
    owner: "root"
    group: "root"
    validate: "visudo -cf %s"
  become: true
  when:
    - wtd_sys_sudo_package_state != "absent"
  tags:
    - sudo
    - configuration
